#!/usr/bin/env python

from __future__ import print_function
from itertools import count
import math
import scipy.integrate as integrate
import numpy as np
import xarray
import re
import sys

import nsuite.stdarg as stdarg
import nsuite.stdattr as stdattr

ra =     1.0   # axial resistivity [Ω m]
rm =     4.0   # membrane resistivity [Ω m²]
cm =    0.01   # memrane specific capacitance [F/m²]
Erev =   -65   # reversal potential [mV]

diam =    1.0  # cable diameter [µm]
length = 1000  # cable length [µm]
iinj =    0.1  # current injection [nA]

tend = 0.25
nsamp = 10000
x0 = 0
x1 = 1

output, tags, params = stdarg.parse_run_stdarg()
if 'dt' in params:
    # params[dt] will be in [ms]; make one sample
    # per integration time step.
    nsamp = 1000*tend/params['dt']
if 'x0' in params:
    x0 = params['x0']
if 'x1' in params:
    x1 = params['x1']

def u(x, t, b, tol):
    if t<=0:
        return 0.0

    uinf = math.cosh(x)/math.sinh(b)

    acc = math.exp(-t)/2
    rtol = tol*t*b

    sign = 1
    for k in count(1):
        a = k*math.pi/b
        l = 1+a*a
        q = math.exp(-l*t)/l
        sign = -sign

        if q<math.sqrt(l)*rtol:
            break

        acc += sign*math.cos(a*x)*q

    return uinf - 2*acc/b


def membrane_voltage(ts, x):
    radius = diam/2
    lam = math.sqrt(rm*radius/(2*ra))*1e3 # [µm]
    tau = rm*cm # [s]
    b = length/lam
    tol = 1e-8
    E = -iinj*ra/(math.pi*radius*radius)

    vs = np.zeros(ts.size)
    for i in range(ts.size):
        vs[i] = Erev - lam*E*u((length-x)/lam, ts[i]/tau, b, tol)

    return vs


ts = np.linspace(0., tend, num=nsamp)
v0 = membrane_voltage(ts, x0*length)
v1 = membrane_voltage(ts, x1*length)

# Rescale ts from [s] to [ms]
ts *= 1000.0

out = xarray.Dataset({'v0': (['time'], v0), 'v1': (['time'], v1)},
                     coords={'time': ts})
out.time.attrs['units'] = 'ms'
out.v0.attrs['units'] = 'mV'
out.v1.attrs['units'] = 'mV'

stdattr.set_stdattr(out, model='rallpack1', simulator='reference', params=params)
out.to_netcdf(output)

